# Generated by Django 3.1 on 2020-08-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='옷이름')),
                ('price', models.IntegerField()),
                ('categories', models.CharField(max_length=128)),
                ('categories_detail', models.CharField(max_length=128)),
                ('buy_count', models.IntegerField()),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'db_table': 'Iver_clothes',
            },
        ),
    ]
