# Generated by Django 3.1 on 2020-08-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='categories_detail',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='categories',
            field=models.IntegerField(),
        ),
    ]
