# Generated by Django 3.1 on 2020-08-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0003_auto_20200818_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Clothes', 'verbose_name_plural': 'Clothes'},
        ),
        migrations.AlterField(
            model_name='clothes',
            name='categories',
            field=models.IntegerField(verbose_name='분류번호'),
        ),
    ]
