# Generated by Django 3.1 on 2020-08-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0004_auto_20200818_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='brand_name',
            field=models.CharField(default=None, max_length=64, verbose_name='브랜드이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.CharField(default=None, max_length=128, verbose_name='옷색깔'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='size',
            field=models.CharField(default=None, max_length=128, verbose_name='옷사이즈'),
            preserve_default=False,
        ),
    ]
