# Generated by Django 3.1 on 2020-08-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0005_auto_20200819_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='brand_name',
            new_name='brandname',
        ),
    ]
