# Generated by Django 3.1 on 2020-08-19 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0006_auto_20200819_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='brandname',
        ),
    ]
