# Generated by Django 3.1 on 2020-08-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0008_clothes_brand_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='color',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='size',
        ),
        migrations.AddField(
            model_name='clothes',
            name='color_size',
            field=models.TextField(default='red / L', verbose_name='옷 색깔 사이즈'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='image',
            field=models.ImageField(default='default', upload_to=''),
            preserve_default=False,
        ),
    ]
