# Generated by Django 3.1 on 2020-08-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0009_auto_20200827_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='description',
            field=models.TextField(default='..', verbose_name='옷 설명'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clothes',
            name='buy_count',
            field=models.IntegerField(verbose_name='구매횟수'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='옷 사진'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='price',
            field=models.IntegerField(verbose_name='옷 가격'),
        ),
    ]
