# Generated by Django 3.1 on 2020-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brand', '0010_auto_20200827_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='image',
            field=models.URLField(verbose_name='옷 사진'),
        ),
    ]
